affected_purls:
- pkg:pypi/oauth2@1.0.0
- pkg:pypi/oauth2@1.0.6
- pkg:pypi/oauth2@1.0.7
- pkg:pypi/oauth2@1.0.8
- pkg:pypi/oauth2@1.0.9
- pkg:pypi/oauth2@1.1.0
- pkg:pypi/oauth2@1.1.1
- pkg:pypi/oauth2@1.1.3
- pkg:pypi/oauth2@1.2.0
- pkg:pypi/oauth2@1.5.150
- pkg:pypi/oauth2@1.5.153
- pkg:pypi/oauth2@1.5.155
- pkg:pypi/oauth2@1.5.158
- pkg:pypi/oauth2@1.5.159
- pkg:pypi/oauth2@1.5.160
- pkg:pypi/oauth2@1.5.161
- pkg:pypi/oauth2@1.5.162
- pkg:pypi/oauth2@1.5.163
- pkg:pypi/oauth2@1.5.164
- pkg:pypi/oauth2@1.5.165
- pkg:pypi/oauth2@1.5.166
- pkg:pypi/oauth2@1.5.167
- pkg:pypi/oauth2@1.5.168
- pkg:pypi/oauth2@1.5.169
- pkg:pypi/oauth2@1.5.170
- pkg:pypi/oauth2@1.5.210
- pkg:pypi/oauth2@1.5.211
aliases:
- CVE-2013-4346
fixed_purl: []
references:
- id: 177121
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-4346
- id: 177122
  reference_id: ''
  url: https://github.com/simplegeo/python-oauth2/issues/129
severities: []
summary: 'Cryptographic Issues

  The `Server.verify_request` function in SimpleGeo python-oauth2 does not check the
  nonce, which allows remote attackers to perform replay attacks via a signed URL.'
vulnerability_id: VCID-1x61-g4t2-aaab
weaknesses: []
