affected_purls:
- pkg:pypi/proxy.py@0.1
- pkg:pypi/proxy.py@0.2
- pkg:pypi/proxy.py@0.3
- pkg:pypi/proxy.py@1.0.0
- pkg:pypi/proxy.py@1.1.0
- pkg:pypi/proxy.py@1.1.1
- pkg:pypi/proxy.py@2.0.0
- pkg:pypi/proxy.py@2.1.1
- pkg:pypi/proxy.py@2.1.2
- pkg:pypi/proxy.py@2.2.0
aliases:
- CVE-2021-3116
- GHSA-cmc7-mfmr-xqrx
fixed_purl:
- pkg:pypi/proxy.py@2.3.1
references:
- id: 160547
  reference_id: ''
  url: https://cardaci.xyz/advisories/2021/01/10/proxy.py-2.3.0-broken-basic-authentication/
- id: 160546
  reference_id: ''
  url: https://github.com/abhinavsingh/proxy.py/pull/482/commits/9b00093288237f5073c403f2c4f62acfdfa8ed46
- id: 160550
  reference_id: ''
  url: https://github.com/pypa/advisory-database/tree/main/vulns/proxy-py/PYSEC-2021-46.yaml
- id: 160548
  reference_id: ''
  url: https://pypi.org/project/proxy.py/2.3.1/#history
- id: 160545
  reference_id: CVE-2021-3116
  url: https://nvd.nist.gov/vuln/detail/CVE-2021-3116
- id: 160549
  reference_id: GHSA-cmc7-mfmr-xqrx
  url: https://github.com/advisories/GHSA-cmc7-mfmr-xqrx
severities:
- id: 23560
  reference_id: 160549
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: Logic error in authentication in proxy.py
vulnerability_id: VCID-xjvu-b63s-aaaf
weaknesses: []
