affected_purls:
- pkg:pypi/urllib3@1.17
- pkg:pypi/urllib3@1.18
aliases:
- CVE-2016-9015
fixed_purl:
- pkg:deb/debian/python-urllib3@0?distro=sid
- pkg:deb/debian/python-urllib3@1.24.1-1?distro=sid
- pkg:deb/debian/python-urllib3@1.26.12-1?distro=sid
- pkg:deb/debian/python-urllib3@1.26.5-1~exp1?distro=sid
- pkg:pypi/urllib3@1.18.1
references:
- id: 177737
  reference_id: ''
  url: http://seclists.org/oss-sec/2016/q4/256
- id: 177738
  reference_id: ''
  url: https://github.com/openssl/openssl/pull/1793
severities: []
summary: Versions 1.17 and 1.18 of the Python urllib3 library suffer from a vulnerability
  that can cause them, in certain configurations, to not correctly validate TLS certificates.
  This places users of the library with those configurations at risk of man-in-the-middle
  and information leakage attacks. This vulnerability affects users using versions
  1.17 and 1.18 of the urllib3 library, who are using the optional PyOpenSSL support
  for TLS instead of the regular standard library TLS backend, and who are using OpenSSL
  1.1.0 via PyOpenSSL. This is an extremely uncommon configuration, so the security
  impact of this vulnerability is low.
vulnerability_id: VCID-r2sn-6xhp-aaaa
weaknesses: []
