affected_purls:
- pkg:pypi/opencv-contrib-python@3.2.0.7
- pkg:pypi/opencv-python@3.2.0.7
- pkg:pypi/opencv-python@3.2.0.8
- pkg:pypi/opencv-python@3.3.0.9
aliases:
- CVE-2017-12864
- GHSA-267x-w5hx-8hjr
fixed_purl:
- pkg:deb/debian/opencv@3.2.0%2Bdfsg-6?distro=sid
- pkg:deb/debian/opencv@4.5.1%2Bdfsg-5?distro=sid
- pkg:deb/debian/opencv@4.6.0%2Bdfsg-12?distro=sid
- pkg:pypi/opencv-contrib-python@3.3.0.10
- pkg:pypi/opencv-python@3.3.0.10
references:
- id: 140960
  reference_id: ''
  url: https://github.com/opencv/opencv/issues/9372
- id: 139477
  reference_id: ''
  url: https://github.com/opencv/opencv/pull/9376
- id: 139476
  reference_id: ''
  url: https://lists.debian.org/debian-lts-announce/2018/07/msg00030.html
- id: 139478
  reference_id: ''
  url: https://lists.debian.org/debian-lts-announce/2021/10/msg00028.html
- id: 140784
  reference_id: ''
  url: https://security.gentoo.org/glsa/201712-02
- id: 126878
  reference_id: '875345'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875345
- id: 140959
  reference_id: CVE-2017-12864
  url: https://nvd.nist.gov/vuln/detail/CVE-2017-12864
- id: 140961
  reference_id: GHSA-267x-w5hx-8hjr
  url: https://github.com/advisories/GHSA-267x-w5hx-8hjr
severities:
- id: 19516
  reference_id: 140961
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not
  checkout the input length, which lead to integer overflow. If the image is from
  remote, may lead to remote code execution or denial of service. This affects Opencv
  3.3 and earlier.
vulnerability_id: VCID-a3rd-85nr-aaan
weaknesses: []
