affected_purls:
- pkg:deb/debian/opencv@3.2.0%2Bdfsg-6
- pkg:pypi/opencv-contrib-python@3.2.0.7
- pkg:pypi/opencv-contrib-python@3.3.0.10
- pkg:pypi/opencv-contrib-python@3.4.1.15
- pkg:pypi/opencv-contrib-python@3.4.2.16
- pkg:pypi/opencv-contrib-python@3.4.2.17
- pkg:pypi/opencv-contrib-python@3.4.3.18
- pkg:pypi/opencv-contrib-python@3.4.4.19
- pkg:pypi/opencv-contrib-python@3.4.5.20
- pkg:pypi/opencv-contrib-python@3.4.6.27
- pkg:pypi/opencv-contrib-python@4.0.0.21
- pkg:pypi/opencv-contrib-python@4.0.1.24
- pkg:pypi/opencv-contrib-python@4.1.0.25
- pkg:pypi/opencv-contrib-python-headless@3.4.1.15
- pkg:pypi/opencv-contrib-python-headless@3.4.2.16
- pkg:pypi/opencv-contrib-python-headless@3.4.2.17
- pkg:pypi/opencv-contrib-python-headless@3.4.3.18
- pkg:pypi/opencv-contrib-python-headless@3.4.4.19
- pkg:pypi/opencv-contrib-python-headless@3.4.5.20
- pkg:pypi/opencv-contrib-python-headless@3.4.6.27
- pkg:pypi/opencv-contrib-python-headless@4.0.0.21
- pkg:pypi/opencv-contrib-python-headless@4.0.1.23
- pkg:pypi/opencv-contrib-python-headless@4.0.1.24
- pkg:pypi/opencv-contrib-python-headless@4.1.0.25
- pkg:pypi/opencv-python@3.2.0.7
- pkg:pypi/opencv-python@3.2.0.8
- pkg:pypi/opencv-python@3.3.0.10
- pkg:pypi/opencv-python@3.3.0.9
- pkg:pypi/opencv-python@3.3.1.11
- pkg:pypi/opencv-python@3.4.0.12
- pkg:pypi/opencv-python@3.4.1.15
- pkg:pypi/opencv-python@3.4.2.16
- pkg:pypi/opencv-python@3.4.2.17
- pkg:pypi/opencv-python@3.4.3.18
- pkg:pypi/opencv-python@3.4.4.19
- pkg:pypi/opencv-python@3.4.5.20
- pkg:pypi/opencv-python@3.4.6.27
- pkg:pypi/opencv-python@4.0.0.21
- pkg:pypi/opencv-python@4.0.1.23
- pkg:pypi/opencv-python@4.0.1.24
- pkg:pypi/opencv-python@4.1.0.25
- pkg:pypi/opencv-python-headless@3.4.2.17
- pkg:pypi/opencv-python-headless@3.4.3.18
- pkg:pypi/opencv-python-headless@3.4.4.19
- pkg:pypi/opencv-python-headless@3.4.5.20
- pkg:pypi/opencv-python-headless@3.4.6.27
- pkg:pypi/opencv-python-headless@4.0.0.21
- pkg:pypi/opencv-python-headless@4.0.1.24
- pkg:pypi/opencv-python-headless@4.1.0.25
aliases:
- CVE-2019-14491
- GHSA-fm39-cw8h-3p63
fixed_purl:
- pkg:deb/debian/opencv@4.5.1%2Bdfsg-5
- pkg:pypi/opencv-contrib-python@3.4.7.28
- pkg:pypi/opencv-contrib-python@4.1.1.26
- pkg:pypi/opencv-contrib-python-headless@3.4.7.28
- pkg:pypi/opencv-contrib-python-headless@4.1.1.26
- pkg:pypi/opencv-python@3.4.7.28
- pkg:pypi/opencv-python@4.1.1.26
- pkg:pypi/opencv-python-headless@3.4.7.28
- pkg:pypi/opencv-python-headless@4.1.1.26
references:
- id: 147938
  reference_id: ''
  url: https://github.com/opencv/opencv/compare/33b765d...4a7ca5a
- id: 147939
  reference_id: ''
  url: https://github.com/opencv/opencv/compare/371bba8...ddbd10c
- id: 147937
  reference_id: ''
  url: https://github.com/opencv/opencv/issues/15125
- id: 147940
  reference_id: ''
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HPFLN6QAX6SUA4XR4NMKKXX26H3TYCVQ/
- id: 147936
  reference_id: CVE-2019-14491
  url: https://nvd.nist.gov/vuln/detail/CVE-2019-14491
- id: 147941
  reference_id: GHSA-fm39-cw8h-3p63
  url: https://github.com/advisories/GHSA-fm39-cw8h-3p63
severities:
- id: 20836
  reference_id: 147941
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There
  is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in
  modules/objdetect/src/cascadedetect.hpp, which leads to denial of service.
vulnerability_id: VCID-67xj-97cx-aaar
weaknesses: []
