affected_purls:
- pkg:pypi/django@2.0
- pkg:pypi/django@2.0.1
- pkg:pypi/django@2.0.10
- pkg:pypi/django@2.0.12
- pkg:pypi/django@2.0.13
- pkg:pypi/django@2.0.2
- pkg:pypi/django@2.0.3
- pkg:pypi/django@2.0.4
- pkg:pypi/django@2.0.5
- pkg:pypi/django@2.0.6
- pkg:pypi/django@2.0.7
- pkg:pypi/django@2.0.8
- pkg:pypi/django@2.0.9
- pkg:pypi/django@2.1
- pkg:pypi/django@2.1.1
- pkg:pypi/django@2.1.10
- pkg:pypi/django@2.1.11
- pkg:pypi/django@2.1.12
- pkg:pypi/django@2.1.13
- pkg:pypi/django@2.1.14
- pkg:pypi/django@2.1.15
- pkg:pypi/django@2.1.2
- pkg:pypi/django@2.1.3
- pkg:pypi/django@2.1.4
- pkg:pypi/django@2.1.5
- pkg:pypi/django@2.1.7
- pkg:pypi/django@2.1.8
- pkg:pypi/django@2.1.9
- pkg:pypi/django@2.1a1
- pkg:pypi/django@2.1b1
- pkg:pypi/django@2.1rc1
- pkg:pypi/django@2.2
- pkg:pypi/django@2.2.1
- pkg:pypi/django@2.2.10
- pkg:pypi/django@2.2.11
- pkg:pypi/django@2.2.12
- pkg:pypi/django@2.2.2
- pkg:pypi/django@2.2.3
- pkg:pypi/django@2.2.4
- pkg:pypi/django@2.2.5
- pkg:pypi/django@2.2.6
- pkg:pypi/django@2.2.7
- pkg:pypi/django@2.2.8
- pkg:pypi/django@2.2.9
- pkg:pypi/django@2.2a1
- pkg:pypi/django@2.2b1
- pkg:pypi/django@2.2rc1
- pkg:pypi/django@3.0
- pkg:pypi/django@3.0.1
- pkg:pypi/django@3.0.2
- pkg:pypi/django@3.0.3
- pkg:pypi/django@3.0.4
- pkg:pypi/django@3.0.5
- pkg:pypi/django@3.0.6
aliases:
- CVE-2020-13254
- GHSA-wpjr-j57x-wxfw
fixed_purl:
- pkg:deb/debian/python-django@1:1.11.29-1~deb10u1?distro=sid
- pkg:deb/debian/python-django@2:2.2.13-1?distro=sid
- pkg:deb/debian/python-django@2:2.2.28-1~deb11u1?distro=sid
- pkg:deb/debian/python-django@3:3.2.19-1?distro=sid
- pkg:pypi/django@2.2.13
- pkg:pypi/django@3.0.7
- pkg:pypi/django@3.0a1
- pkg:pypi/django@3.1a1
references:
- id: 150721
  reference_id: ''
  url: https://docs.djangoproject.com/en/3.0/releases/security/
- id: 150730
  reference_id: ''
  url: https://github.com/django/django/commit/07e59caa02831c4569bbebb9eb773bdd9cb4b206
- id: 150731
  reference_id: ''
  url: https://github.com/django/django/commit/84b2da5552e100ae3294f564f6c862fef8d0e693
- id: 150722
  reference_id: ''
  url: https://groups.google.com/d/msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ
- id: 150724
  reference_id: ''
  url: https://lists.debian.org/debian-lts-announce/2020/06/msg00016.html
- id: 150725
  reference_id: ''
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/
- id: 150726
  reference_id: ''
  url: https://security.netapp.com/advisory/ntap-20200611-0002/
- id: 150727
  reference_id: ''
  url: https://usn.ubuntu.com/4381-1/
- id: 150728
  reference_id: ''
  url: https://usn.ubuntu.com/4381-2/
- id: 150729
  reference_id: ''
  url: https://www.debian.org/security/2020/dsa-4705
- id: 150723
  reference_id: ''
  url: https://www.djangoproject.com/weblog/2020/jun/03/security-releases/
- id: 134377
  reference_id: ''
  url: https://www.oracle.com/security-alerts/cpujan2021.html
- id: 129124
  reference_id: '962323'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962323
- id: 150720
  reference_id: CVE-2020-13254
  url: https://nvd.nist.gov/vuln/detail/CVE-2020-13254
- id: 150732
  reference_id: GHSA-wpjr-j57x-wxfw
  url: https://github.com/advisories/GHSA-wpjr-j57x-wxfw
severities:
- id: 21364
  reference_id: 150732
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7.
  In cases where a memcached backend does not perform key validation, passing malformed
  cache keys could result in a key collision, and potential data leakage.
vulnerability_id: VCID-kfhg-p2xd-aaan
weaknesses: []
