affected_purls:
- pkg:pypi/django@2.2
- pkg:pypi/django@2.2.1
- pkg:pypi/django@2.2.10
- pkg:pypi/django@2.2.11
- pkg:pypi/django@2.2.12
- pkg:pypi/django@2.2.13
- pkg:pypi/django@2.2.14
- pkg:pypi/django@2.2.15
- pkg:pypi/django@2.2.16
- pkg:pypi/django@2.2.17
- pkg:pypi/django@2.2.18
- pkg:pypi/django@2.2.19
- pkg:pypi/django@2.2.2
- pkg:pypi/django@2.2.20
- pkg:pypi/django@2.2.21
- pkg:pypi/django@2.2.22
- pkg:pypi/django@2.2.23
- pkg:pypi/django@2.2.24
- pkg:pypi/django@2.2.25
- pkg:pypi/django@2.2.3
- pkg:pypi/django@2.2.4
- pkg:pypi/django@2.2.5
- pkg:pypi/django@2.2.6
- pkg:pypi/django@2.2.7
- pkg:pypi/django@2.2.8
- pkg:pypi/django@2.2.9
- pkg:pypi/django@3.2
- pkg:pypi/django@3.2.1
- pkg:pypi/django@3.2.10
- pkg:pypi/django@3.2.2
- pkg:pypi/django@3.2.3
- pkg:pypi/django@3.2.4
- pkg:pypi/django@3.2.5
- pkg:pypi/django@3.2.6
- pkg:pypi/django@3.2.7
- pkg:pypi/django@3.2.8
- pkg:pypi/django@3.2.9
- pkg:pypi/django@4.0
aliases:
- CVE-2021-45116
- GHSA-8c5j-9r9f-c6w8
fixed_purl:
- pkg:deb/debian/python-django@1:1.11.29-1~deb10u1?distro=sid
- pkg:deb/debian/python-django@1:1.11.29-1%2Bdeb10u3?distro=sid
- pkg:deb/debian/python-django@2:2.2.26-1~deb11u1?distro=sid
- pkg:deb/debian/python-django@2:2.2.28-1~deb11u1?distro=sid
- pkg:deb/debian/python-django@2:3.2.11-1?distro=sid
- pkg:deb/debian/python-django@3:3.2.19-1?distro=sid
- pkg:pypi/django@2.2.26
- pkg:pypi/django@3.2.11
- pkg:pypi/django@4.0.1
references:
- id: 164962
  reference_id: ''
  url: https://docs.djangoproject.com/en/4.0/releases/security/
- id: 164967
  reference_id: ''
  url: https://github.com/django/django/commit/2a8ec7f546d6d5806e221ec948c5146b55bd7489
- id: 164968
  reference_id: ''
  url: https://github.com/django/django/commit/c7fe895bca06daf12cc1670b56eaf72a1ef27a16
- id: 164969
  reference_id: ''
  url: https://github.com/django/django/commit/c9f648ccfac5ab90fb2829a66da4f77e68c7f93a
- id: 160622
  reference_id: ''
  url: https://groups.google.com/forum/#!forum/django-announce
- id: 160627
  reference_id: ''
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/
- id: 164964
  reference_id: ''
  url: https://security.netapp.com/advisory/ntap-20220121-0005/
- id: 164963
  reference_id: ''
  url: https://www.djangoproject.com/weblog/2022/jan/04/security-releases/
- id: 130129
  reference_id: '1003113'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003113
- id: 164966
  reference_id: CVE-2021-45116
  url: https://nvd.nist.gov/vuln/detail/CVE-2021-45116
- id: 164970
  reference_id: GHSA-8c5j-9r9f-c6w8
  url: https://github.com/advisories/GHSA-8c5j-9r9f-c6w8
severities:
- id: 24797
  reference_id: 164970
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and
  4.0 before 4.0.1. Due to leveraging the Django Template Language's variable resolution
  logic, the dictsort template filter was potentially vulnerable to information disclosure,
  or an unintended method call, if passed a suitably crafted key.
vulnerability_id: VCID-bjyh-4gt9-aaan
weaknesses: []
