affected_purls:
- pkg:deb/debian/libapache2-mod-python@3.1.3-3
aliases:
- CVE-2004-2680
fixed_purl:
- pkg:deb/debian/libapache2-mod-python@3.2.10-4
- pkg:deb/debian/libapache2-mod-python@3.2.8-1?distro=sid
- pkg:deb/debian/libapache2-mod-python@3.3.1-11?distro=sid
- pkg:deb/debian/libapache2-mod-python@3.5.0-1?distro=sid
- pkg:deb/debian/libapache2-mod-python@3.5.0%2Bgit20211031.e6458ec-1?distro=sid
references:
- id: 69783
  reference_id: ''
  url: http://mail-archives.apache.org/mod_mbox/httpd-python-dev/200404.mbox/%3c6DCA8C14-8FFA-11D8-8B4E-000A95B0D772@pixar.com%3e
- id: 69782
  reference_id: ''
  url: http://mail-archives.apache.org/mod_mbox/httpd-python-dev/200404.mbox/%3cCD485B27-8F3E-11D8-934B-000A95B0D772@pixar.com%3e
- id: 69784
  reference_id: ''
  url: http://mail-archives.apache.org/mod_mbox/httpd-python-dev/200404.mbox/%3cEB279100-9000-11D8-8B4E-000A95B0D772@pixar.com%3e
- id: 69797
  reference_id: ''
  url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2004-2680.json
- id: 69795
  reference_id: ''
  url: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2004-2680
- id: 69791
  reference_id: ''
  url: http://secunia.com/advisories/24418
- id: 69790
  reference_id: ''
  url: http://secunia.com/advisories/24424
- id: 69793
  reference_id: ''
  url: https://exchange.xforce.ibmcloud.com/vulnerabilities/14751
- id: 69786
  reference_id: ''
  url: https://issues.rpath.com/browse/RPL-1105
- id: 69785
  reference_id: ''
  url: https://launchpad.net/bugs/89308
- id: 69787
  reference_id: ''
  url: http://svn.apache.org/viewvc/httpd/mod_python/trunk/src/filterobject.c?r1=102649&r2=103561&pathrev=103561
- id: 69794
  reference_id: ''
  url: http://www.securityfocus.com/archive/1/462185/100/0/threaded
- id: 69789
  reference_id: ''
  url: http://www.securityfocus.com/bid/22849
- id: 69788
  reference_id: ''
  url: http://www.ubuntu.com/usn/usn-430-1
- id: 69792
  reference_id: ''
  url: http://www.vupen.com/english/advisories/2007/0846
- id: 69796
  reference_id: '231065'
  url: https://bugzilla.redhat.com/show_bug.cgi?id=231065
- id: 23026
  reference_id: cpe:2.3:a:apache:mod_python:*:*:*:*:*:*:*:*
  url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:apache:mod_python:*:*:*:*:*:*:*:*
- id: 69781
  reference_id: CVE-2004-2680
  url: https://nvd.nist.gov/vuln/detail/CVE-2004-2680
- id: 69798
  reference_id: USN-430-1
  url: https://usn.ubuntu.com/430-1/
severities:
- id: 10367
  reference_id: 69781
  scoring_elements: AV:N/AC:L/Au:N/C:P/I:N/A:N
  scoring_system: cvssv2
  value: '5.0'
summary: mod_python (libapache2-mod-python) 3.1.4 and earlier does not properly handle
  when output filters process more than 16384 bytes, which can cause filter.read to
  return portions of previously freed memory.
vulnerability_id: VCID-5vgj-sz1w-aaad
weaknesses: []
