affected_purls:
- pkg:deb/debian/python-pysaml2@4.5.0-4%2Bdeb10u1
- pkg:pypi/pysaml2@0.4.3
- pkg:pypi/pysaml2@1.0.1
- pkg:pypi/pysaml2@1.0.2
- pkg:pypi/pysaml2@1.0.3
- pkg:pypi/pysaml2@1.1.0
- pkg:pypi/pysaml2@2.0.0
- pkg:pypi/pysaml2@2.1.0
- pkg:pypi/pysaml2@2.2.0
- pkg:pypi/pysaml2@2.3.0
- pkg:pypi/pysaml2@2.4.0
- pkg:pypi/pysaml2@3.0.0
- pkg:pypi/pysaml2@3.0.2
- pkg:pypi/pysaml2@4.0.0
- pkg:pypi/pysaml2@4.0.1
- pkg:pypi/pysaml2@4.0.2
- pkg:pypi/pysaml2@4.0.3
- pkg:pypi/pysaml2@4.0.4
- pkg:pypi/pysaml2@4.0.5
- pkg:pypi/pysaml2@4.0.5rc1
- pkg:pypi/pysaml2@4.1.0
- pkg:pypi/pysaml2@4.2.0
- pkg:pypi/pysaml2@4.3.0
- pkg:pypi/pysaml2@4.4.0
- pkg:pypi/pysaml2@4.5.0
- pkg:pypi/pysaml2@4.6.0
- pkg:pypi/pysaml2@4.6.1
- pkg:pypi/pysaml2@4.6.2
- pkg:pypi/pysaml2@4.6.3
- pkg:pypi/pysaml2@4.6.4
- pkg:pypi/pysaml2@4.6.5
- pkg:pypi/pysaml2@4.7.0
- pkg:pypi/pysaml2@4.8.0
- pkg:pypi/pysaml2@4.9.0
- pkg:pypi/pysaml2@5.0.0
- pkg:pypi/pysaml2@5.1.0
- pkg:pypi/pysaml2@5.2.0
- pkg:pypi/pysaml2@5.3.0
- pkg:pypi/pysaml2@5.4.0
- pkg:pypi/pysaml2@6.0.0
- pkg:pypi/pysaml2@6.1.0
- pkg:pypi/pysaml2@6.2.0
- pkg:pypi/pysaml2@6.3.0
- pkg:pypi/pysaml2@6.3.1
- pkg:pypi/pysaml2@6.4.0
- pkg:pypi/pysaml2@6.4.1
aliases:
- CVE-2021-21239
- GHSA-5p3x-r448-pc62
fixed_purl:
- pkg:deb/debian/python-pysaml2@6.5.1-1
- pkg:pypi/pysaml2@6.5.0
references:
- id: 156773
  reference_id: ''
  url: https://github.com/IdentityPython/pysaml2/commit/46578df0695269a16f1c94171f1429873f90ed99
- id: 156768
  reference_id: ''
  url: https://github.com/IdentityPython/pysaml2/releases/tag/v6.5.0
- id: 140560
  reference_id: ''
  url: https://lists.debian.org/debian-lts-announce/2021/02/msg00038.html
- id: 156769
  reference_id: ''
  url: https://pypi.org/project/pysaml2
- id: 156774
  reference_id: ''
  url: https://www.aleksey.com/pipermail/xmlsec/2013/009717.html
- id: 129607
  reference_id: '980772'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980772
- id: 156775
  reference_id: CVE-2021-21239
  url: https://nvd.nist.gov/vuln/detail/CVE-2021-21239
- id: 156776
  reference_id: GHSA-5p3x-r448-pc62
  url: https://github.com/advisories/GHSA-5p3x-r448-pc62
- id: 156772
  reference_id: GHSA-5p3x-r448-pc62
  url: https://github.com/IdentityPython/pysaml2/security/advisories/GHSA-5p3x-r448-pc62
severities:
- id: 22635
  reference_id: 156776
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
- id: 22634
  reference_id: 156772
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: PySAML2 is a pure python implementation of SAML Version 2 Standard. PySAML2
  before 6.5.0 has an improper verification of cryptographic signature vulnerability.
  Users of pysaml2 that use the default CryptoBackendXmlSec1 backend and need to verify
  signed SAML documents are impacted. PySAML2 does not ensure that a signed SAML document
  is correctly signed. The default CryptoBackendXmlSec1 backend is using the xmlsec1
  binary to verify the signature of signed SAML documents, but by default xmlsec1
  accepts any type of key found within the given document. xmlsec1 needs to be configured
  explicitly to only use only _x509 certificates_ for the verification process of
  the SAML document signature. This is fixed in PySAML2 6.5.0.
vulnerability_id: VCID-jz5q-b8v8-aaab
weaknesses: []
